In [10]:
import torch
import torch.nn as nn

In [21]:
a = torch.arange(12).view(3, 4)
funcs = [torch.sin, torch.cos]
L = 3
out = [a]
# for i in range(L):
    

In [13]:
out

[tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0.0000,  0.8415,  0.9093,  0.1411],
         [-0.7568, -0.9589, -0.2794,  0.6570],
         [ 0.9894,  0.4121, -0.5440, -1.0000]]),
 tensor([[ 1.0000,  0.5403, -0.4161, -0.9900],
         [-0.6536,  0.2837,  0.9602,  0.7539],
         [-0.1455, -0.9111, -0.8391,  0.0044]]),
 tensor([[ 0.0000,  0.9093, -0.7568, -0.2794],
         [ 0.9894, -0.5440, -0.5366,  0.9906],
         [-0.2879, -0.7510,  0.9129, -0.0089]]),
 tensor([[ 1.0000, -0.4161, -0.6536,  0.9602],
         [-0.1455, -0.8391,  0.8439,  0.1367],
         [-0.9577,  0.6603,  0.4081, -1.0000]]),
 tensor([[ 0.0000, -0.7568,  0.9894, -0.5366],
         [-0.2879,  0.9129, -0.9056,  0.2709],
         [ 0.5514, -0.9918,  0.7451,  0.0177]]),
 tensor([[ 1.0000, -0.6536, -0.1455,  0.8439],
         [-0.9577,  0.4081,  0.4242, -0.9626],
         [ 0.8342, -0.1280, -0.6669,  0.9998]])]

In [18]:
torch.linspace(0, 10, 11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
torch.linspace(2 ** 0, 2 ** (3 - 1), 3)

tensor([1.0000, 2.5000, 4.0000])

In [20]:
torch.linspace(1, 2**(3-1), 3)

tensor([1.0000, 2.5000, 4.0000])